//
// Created by Marcel on 23.01.2024.
//

#ifndef SSSP_NEAR_LINEAR_TIME_SHORTEST_PATH_ALGORITHM_H
#define SSSP_NEAR_LINEAR_TIME_SHORTEST_PATH_ALGORITHM_H

#endif //SSSP_NEAR_LINEAR_TIME_SHORTEST_PATH_ALGORITHM_H
